apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: myapp
spec:
    containers:
    - name: mysql
      image: mysql
      imagePullPolicy: IfNotPresent
      env:
      - name: BACKEND_HOST
        value: localhost:8080
      ports:
      - containerPort: 80
